[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/newuser"
  to = "/newuser/index.html"
  status = 200

[[redirects]]
  from = "/user"
  to = "/user/index.html"
  status = 200
